import {
  ASSETS,
  BARREL_EXPLOSION_FRAMES,
  DEBRIS_ASSETS,
  ENVIRONMENT_SEGMENT_SIZE,
  EFFECT_FRAMES,
  EXPLOSION_FRAMES,
  LOOT_RAM_FRAMES,
  MONSTER_FRAMES,
  PLAYER_FRAMES,
  PORTAL_FRAMES,
  SCENERY_ASSETS,
  WEAPON_ASSETS,
  type MonsterFrameSet,
} from "../config";
import type {
  ActorVisualDefinition,
  BossKind,
  LootKind,
  MonsterAttackPattern,
  ObjectVisualDefinition,
  PlayerDirection,
  RegularMonsterKind,
  RoomShape,
  SpriteClip,
  SpriteDirection,
  WeaponKind,
  WeaponPlacement,
  ObjectGeometry,
} from "../types";

const circle = (radius: number) => ({ x: radius, y: radius });

const clip = (
  frames: readonly string[],
  sizeScale = 1,
  origin = { x: 0.5, y: 0.5 },
  frameDurationMs = 100,
  options: Pick<SpriteClip, "loop" | "holdLast" | "eventFrame" | "light"> = {},
): SpriteClip => ({ frames, sizeScale, origin, frameDurationMs, ...options });

const damageEffect = (sizeScale = 0.4): SpriteClip =>
  clip(EFFECT_FRAMES.damage, sizeScale, { x: 0.5, y: 0.5 }, 100, {
    light: { color: 0xff526b, radiusScale: 0.7, intensity: 1.15 },
  });
const explosionEffect = (sizeScale = 0.8): SpriteClip =>
  clip(EXPLOSION_FRAMES, sizeScale, { x: 0.5, y: 0.5 }, 1_000 / 12, {
    light: { color: 0xffa34d, radiusScale: 1.15, intensity: 1.5 },
  });
const monsterDebris = (assets: readonly string[], sizeScale: number): readonly SpriteClip[] =>
  assets.map(asset => clip([asset], sizeScale));

function monsterDirections(frames: MonsterFrameSet): ActorVisualDefinition["directions"] {
  return Object.fromEntries(
    Object.entries(frames).map(([direction, directionalFrames]) => [direction, {
      normal: clip(directionalFrames.normal),
      ...(directionalFrames.walk
        ? { walk: clip(directionalFrames.walk, 1, undefined, 125, { loop: true }) }
        : {}),
      ...(directionalFrames.melee
        ? { melee: clip(directionalFrames.melee, 1, undefined, 125, { eventFrame: 2 }) }
        : {}),
      ...(directionalFrames.ranged
        ? { ranged: clip(directionalFrames.ranged, 1, undefined, 125, { eventFrame: 2 }) }
        : {}),
    }]),
  ) as Record<SpriteDirection, ActorVisualDefinition["directions"][string]>;
}

const monsterEffects = { damage: damageEffect(0.32), destroy: explosionEffect(0.78) };

export const WORLD_GEOMETRY = {
  segmentSize: ENVIRONMENT_SEGMENT_SIZE,
  floorTileSize: 64,
  doorSpanSegmentsVertical: 3,
  doorSpanSegmentsHorizontal: 2,
  doorOpeningWidth: ENVIRONMENT_SEGMENT_SIZE * 1,
  wallThickness: 25,
  corridorHalfWidth: ENVIRONMENT_SEGMENT_SIZE,
  verticalDoorPassableOffsetY: -10,
  roomCollisionMargin: 4,
  spatialCellSize: 366,
  pathGridStep: 13,
  pathLineStep: 17,
  pathBoundsPadding: 129,
} as const;

export const ROOM_DEFINITIONS: Record<RoomShape | "boss", { width: number; height: number }> = {
  rectangle: { width: ENVIRONMENT_SEGMENT_SIZE * 4, height: ENVIRONMENT_SEGMENT_SIZE * 4 },
  wide: { width: ENVIRONMENT_SEGMENT_SIZE * 8, height: ENVIRONMENT_SEGMENT_SIZE * 4 },
  tall: { width: ENVIRONMENT_SEGMENT_SIZE * 4, height: ENVIRONMENT_SEGMENT_SIZE * 8 },
  capsule: { width: ENVIRONMENT_SEGMENT_SIZE * 4, height: ENVIRONMENT_SEGMENT_SIZE * 4 },
  octagon: { width: ENVIRONMENT_SEGMENT_SIZE * 4, height: ENVIRONMENT_SEGMENT_SIZE * 4 },
  boss: { width: ENVIRONMENT_SEGMENT_SIZE * 8, height: ENVIRONMENT_SEGMENT_SIZE * 8 },
};

const PLAYER_ORIGIN = { x: 0.5, y: 0.90625 };
const PLAYER_WALK_ORIGIN = { x: 0.5, y: 0.90625 };
const PLAYER_VISUAL: ActorVisualDefinition = {
  directions: Object.fromEntries(
    Object.entries(PLAYER_FRAMES).map(([direction, frames]) => [direction, {
      normal: clip(frames.normal, 1, PLAYER_ORIGIN),
      walk: clip(frames.walk, 1, PLAYER_WALK_ORIGIN, 125, { loop: true }),
    }]),
  ) as Record<PlayerDirection, ActorVisualDefinition["directions"][string]>,
  effects: {
    damage: clip(EFFECT_FRAMES.damage, 72 / 190, { x: 0.5, y: 0.5 }, 100, {
      light: { color: 0xff526b, radiusScale: 0.7, intensity: 1.15 },
    }),
    healing: clip(EFFECT_FRAMES.healing, 112 / 190, { x: 0.5, y: 0.5 }, 100, {
      light: { color: 0x70ffd2, radiusScale: 0.85, intensity: 1.2 },
    }),
    teleport: clip(EFFECT_FRAMES.teleport, 150 / 190, { x: 0.5, y: 0.5 }, 100, {
      light: { color: 0x72d6ff, radiusScale: 1.05, intensity: 1.35 },
    }),
  },
};

export const PLAYER_SPEC = {
  obstacle: true,
  visualOffset: { x: 0, y: -60 },
  hitboxOffset: { x: 0, y: -25 },
  hitboxRadii: circle(28),
  footprintRadii: circle(20),
  spriteSize: 190,
  visual: PLAYER_VISUAL,
  muzzleDistance: 21,
  speed: 400,
  maxHp: 10,
} as const;

export const DEFAULT_BULLET_SPEC = {
  radius: 6,
  maxDistance: 1_029,
} as const;

export const BARREL_EXPLOSION_RADIUS = 115;
export const BARREL_EXPLOSION_DAMAGE = 6;

export const CRYSTAL_INVULNERABILITY_DURATION_MS = 10_000;
export const CRYSTAL_INVULNERABILITY_BLINK_START_MS = 2_000;
export const PLAYER_DAMAGE_INVULNERABILITY_MS = 200;

export const PLAYER_ENERGY_MAX = 10;
export const ENERGY_DASH_DISTANCE_PER_ENERGY = WORLD_GEOMETRY.segmentSize * 0.75;
export const ENERGY_DASH_SPEED = 1_300;
export const ENERGY_DASH_DAMAGE_PER_ENERGY = 23.5 / 5;
export const ENERGY_DASH_TURN_RATE = Math.PI * 2;

interface MonsterDefinition {
  obstacle: boolean;
  visualOffset: ObjectGeometry["visualOffset"];
  destroyedVisualOffset: ObjectGeometry["visualOffset"];
  hitboxOffset: ObjectGeometry["hitboxOffset"];
  hitboxRadii: ObjectGeometry["hitboxRadii"];
  footprintRadii: ObjectGeometry["footprintRadii"];
  kind: RegularMonsterKind;
  visual: ActorVisualDefinition;
  attackPattern: MonsterAttackPattern;
  fast: boolean;
  size: number;
  spriteSize: number;
  healthBarOffsetY: number;
  baseHp: number;
  hpVariance: number;
  speed: number;
  speedPerDifficulty: number;
  maxSpeedBonus: number;
  attackRange: number;
  attackRangePerDifficulty: number;
  maxAttackRangeBonus: number;
  attackDamage: number;
  attackCooldownMs: number;
  attackCooldownVarianceMs?: number;
  cooldownReductionPerDifficulty: number;
  minAttackCooldownMs: number;
  projectileSpeed: number;
  projectileSpeedPerDifficulty: number;
  maxProjectileSpeedBonus: number;
  projectileRange: number;
  projectileRangePerDifficulty: number;
  maxProjectileRangeBonus: number;
}

export const REGULAR_MONSTER_DEFINITIONS: Record<RegularMonsterKind, MonsterDefinition> = {
  "melee-heavy": {
    kind: "melee-heavy",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.heavy),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.heavyWreck, DEBRIS_ASSETS.heavyParts, DEBRIS_ASSETS.robotLegs, DEBRIS_ASSETS.servoMotors], 0.72),
    },
    attackPattern: "melee",
    fast: false,
    obstacle: true,
    visualOffset: { x: 0, y: -50 },
    destroyedVisualOffset: { x: 0, y: -72.45 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 50, y: 50 },
    footprintRadii: { x: 50, y: 50 },
    size: 230,
    spriteSize: 230,
    healthBarOffsetY: -104.6,
    baseHp: 8,
    hpVariance: 5,
    speed: 120,
    speedPerDifficulty: 6,
    maxSpeedBonus: 60,
    attackRange: 40,
    attackRangePerDifficulty: 2,
    maxAttackRangeBonus: 24,
    attackDamage: 3,
    attackCooldownMs: 1_250,
    cooldownReductionPerDifficulty: 25,
    minAttackCooldownMs: 700,
    projectileSpeed: 0,
    projectileSpeedPerDifficulty: 0,
    maxProjectileSpeedBonus: 0,
    projectileRange: 0,
    projectileRangePerDifficulty: 0,
    maxProjectileRangeBonus: 0,
  },
  "melee-light": {
    kind: "melee-light",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.scout),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.scoutWreck, DEBRIS_ASSETS.scoutParts, DEBRIS_ASSETS.spiderChassis], 0.72),
    },
    attackPattern: "melee",
    fast: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    destroyedVisualOffset: { x: 0, y: -47.25 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 25, y: 25 },
    footprintRadii: { x: 25, y: 25 },
    size: 150,
    spriteSize: 150,
    healthBarOffsetY: -71,
    baseHp: 2,
    hpVariance: 3,
    speed: 250,
    speedPerDifficulty: 10,
    maxSpeedBonus: 100,
    attackRange: 30,
    attackRangePerDifficulty: 3,
    maxAttackRangeBonus: 32,
    attackDamage: 1,
    attackCooldownMs: 750,
    cooldownReductionPerDifficulty: 20,
    minAttackCooldownMs: 400,
    projectileSpeed: 0,
    projectileSpeedPerDifficulty: 0,
    maxProjectileSpeedBonus: 0,
    projectileRange: 0,
    projectileRangePerDifficulty: 0,
    maxProjectileRangeBonus: 0,
  },
  "shooter-light": {
    kind: "shooter-light",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.scout),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.scoutWreck, DEBRIS_ASSETS.scoutParts, DEBRIS_ASSETS.spiderChassis], 0.72),
    },
    attackPattern: "single",
    fast: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    destroyedVisualOffset: { x: 0, y: -47.25 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 25, y: 25 },
    footprintRadii: { x: 25, y: 25 },
    size: 150,
    spriteSize: 150,
    healthBarOffsetY: -71,
    baseHp: 2,
    hpVariance: 3,
    speed: 250,
    speedPerDifficulty: 10,
    maxSpeedBonus: 100,
    attackRange: 400,
    attackRangePerDifficulty: 10,
    maxAttackRangeBonus: 100,
    attackDamage: 1,
    attackCooldownMs: 800,
    cooldownReductionPerDifficulty: 20,
    minAttackCooldownMs: 300,
    projectileSpeed: 280,
    projectileSpeedPerDifficulty: 20,
    maxProjectileSpeedBonus: 150,
    projectileRange: 400,
    projectileRangePerDifficulty: 20,
    maxProjectileRangeBonus: 200,
  },
  "shooter-heavy": {
    kind: "shooter-heavy",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.heavy),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.heavyWreck, DEBRIS_ASSETS.heavyParts, DEBRIS_ASSETS.robotLegs, DEBRIS_ASSETS.servoMotors], 0.72),
    },
    attackPattern: "single",
    fast: false,
    obstacle: true,
    visualOffset: { x: 0, y: -50 },
    destroyedVisualOffset: { x: 0, y: -72.45 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 50, y: 50 },
    footprintRadii: { x: 50, y: 50 },
    size: 230,
    spriteSize: 230,
    healthBarOffsetY: -104.6,
    baseHp: 8,
    hpVariance: 5,
    speed: 120,
    speedPerDifficulty: 6,
    maxSpeedBonus: 60,
    attackRange: 400,
    attackRangePerDifficulty: 20,
    maxAttackRangeBonus: 100,
    attackDamage: 3,
    attackCooldownMs: 1_000,
    cooldownReductionPerDifficulty: 30,
    minAttackCooldownMs: 500,
    projectileSpeed: 250,
    projectileSpeedPerDifficulty: 10,
    maxProjectileSpeedBonus: 120,
    projectileRange: 400,
    projectileRangePerDifficulty: 20,
    maxProjectileRangeBonus: 200,
  },
  "sentry-light": {
    kind: "sentry-light",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.sentryBallistic),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.sentryBallisticWreck, DEBRIS_ASSETS.sentryBallisticParts, DEBRIS_ASSETS.turretHousing], 0.72),
    },
    attackPattern: "single",
    fast: false,
    obstacle: true,
    visualOffset: { x: 0, y: -70 },
    destroyedVisualOffset: { x: 0, y: -55.125 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 40, y: 40 },
    footprintRadii: { x: 35, y: 35 },
    size: 175,
    spriteSize: 248.5,
    healthBarOffsetY: -85,
    baseHp: 3,
    hpVariance: 3,
    speed: 0,
    speedPerDifficulty: 0,
    maxSpeedBonus: 0,
    attackRange: 500,
    attackRangePerDifficulty: 20,
    maxAttackRangeBonus: 200,
    attackDamage: 1,
    attackCooldownMs: 700,
    attackCooldownVarianceMs: 0,
    cooldownReductionPerDifficulty: 0,
    minAttackCooldownMs: 400,
    projectileSpeed: 250,
    projectileSpeedPerDifficulty: 20,
    maxProjectileSpeedBonus: 150,
    projectileRange: 500,
    projectileRangePerDifficulty: 20,
    maxProjectileRangeBonus: 200,
  },
  "sentry-heavy": {
    kind: "sentry-heavy",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.sentryTwin),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.sentryTwinWreck, DEBRIS_ASSETS.sentryTwinParts, DEBRIS_ASSETS.turretHousing], 0.72),
    },
    attackPattern: "double",
    fast: false,
    obstacle: true,
    visualOffset: { x: 0, y: -80 },
    destroyedVisualOffset: { x: 0, y: -63 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 50, y: 50 },
    footprintRadii: { x: 35, y: 35 },
    size: 200,
    spriteSize: 268,
    healthBarOffsetY: -78,
    baseHp: 10,
    hpVariance: 5,
    speed: 0,
    speedPerDifficulty: 0,
    maxSpeedBonus: 0,
    attackRange: 600,
    attackRangePerDifficulty: 20,
    maxAttackRangeBonus: 200,
    attackDamage: 1,
    attackCooldownMs: 850,
    cooldownReductionPerDifficulty: 12,
    minAttackCooldownMs: 600,
    projectileSpeed: 300,
    projectileSpeedPerDifficulty: 20,
    maxProjectileSpeedBonus: 150,
    projectileRange: 600,
    projectileRangePerDifficulty: 20,
    maxProjectileRangeBonus: 200,
  },
  "sentry-scatter": {
    kind: "sentry-scatter",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.sentryEnergy),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.sentryEnergyWreck, DEBRIS_ASSETS.sentryEnergyParts, DEBRIS_ASSETS.purpleEnergyCoil], 0.72),
    },
    attackPattern: "scatter",
    fast: false,
    obstacle: true,
    visualOffset: { x: 0, y: -50 },
    destroyedVisualOffset: { x: 0, y: -47.25 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 35, y: 35 },
    footprintRadii: { x: 30, y: 30 },
    size: 150,
    spriteSize: 180,
    healthBarOffsetY: -74,
    baseHp: 6,
    hpVariance: 4,
    speed: 0,
    speedPerDifficulty: 0,
    maxSpeedBonus: 0,
    attackRange: 400,
    attackRangePerDifficulty: 20,
    maxAttackRangeBonus: 200,
    attackDamage: 2,
    attackCooldownMs: 1_600,
    cooldownReductionPerDifficulty: 20,
    minAttackCooldownMs: 1_100,
    projectileSpeed: 240,
    projectileSpeedPerDifficulty: 20,
    maxProjectileSpeedBonus: 120,
    projectileRange: 400,
    projectileRangePerDifficulty: 20,
    maxProjectileRangeBonus: 200,
  },
};

export const MAX_REGULAR_MONSTER_FOOTPRINT = Math.max(
  ...Object.values(REGULAR_MONSTER_DEFINITIONS).map(definition => Math.max(definition.footprintRadii.x, definition.footprintRadii.y)),
);

export const MINIBOSS_CHANCE_PERCENT = 5;
export const MINIBOSS_HP_MULTIPLIER = 3;
export const MINIBOSS_DAMAGE_MULTIPLIER = 1.5;
export const MINIBOSS_SIZE_MULTIPLIER = 1.4;

export const MONSTER_SPAWN_PROFILES = {
  room: { hpBonus: 0, speedPercent: 100, rangePercent: 100, cooldownPercent: 100, dropsLoot: true },
  spawner: { hpBonus: 1, speedPercent: 110, rangePercent: 105, cooldownPercent: 90, dropsLoot: false },
  summon: { hpBonus: 1, speedPercent: 112, rangePercent: 95, cooldownPercent: 94, dropsLoot: false },
} as const;

interface BossDefinition {
  obstacle: boolean;
  visualOffset: ObjectGeometry["visualOffset"];
  destroyedVisualOffset: ObjectGeometry["visualOffset"];
  hitboxOffset: ObjectGeometry["hitboxOffset"];
  hitboxRadii: ObjectGeometry["hitboxRadii"];
  footprintRadii: ObjectGeometry["footprintRadii"];
  kind: BossKind;
  visual: ActorVisualDefinition;
  label: string;
  color: number;
  size: number;
  spriteSize: number;
  healthBarOffsetY: number;
  baseHp: number;
  hpPerDifficulty: number;
  hpVariance: number;
  speed: number;
  speedPerDifficulty: number;
  maxSpeedBonus: number;
  attackRange: number;
  attackDamage: number;
  attackDamageDifficultyDivisor: number;
  attackCooldownMs: number;
  cooldownReductionPerDifficulty: number;
  minAttackCooldownMs: number;
  projectileSpeed: number;
  projectileSpeedPerDifficulty: number;
  projectileRange: number;
}

export const BOSS_DEFINITIONS: Record<BossKind, BossDefinition> = {
  "deepseek-summoner": {
    kind: "deepseek-summoner",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.bossArc),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.bossArcWreck, DEBRIS_ASSETS.bossArcParts], 0.5),
    },
    label: "DEEPSEEK",
    color: 0xd975ff,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    destroyedVisualOffset: { x: 0, y: -67.8125 },
    hitboxOffset: { x: 0, y: -50 },
    hitboxRadii: { x: 64, y: 64 },
    footprintRadii: { x: 90, y: 90 },
    size: 310,
    spriteSize: 310,
    healthBarOffsetY: -269.5625,
    baseHp: 60,
    hpPerDifficulty: 8,
    hpVariance: 12,
    speed: 160,
    speedPerDifficulty: 5,
    maxSpeedBonus: 50,
    attackRange: 100,
    attackDamage: 1,
    attackDamageDifficultyDivisor: 3,
    attackCooldownMs: 2_000,
    cooldownReductionPerDifficulty: 30,
    minAttackCooldownMs: 1_600,
    projectileSpeed: 190,
    projectileSpeedPerDifficulty: 14,
    projectileRange: 900,
  },
  "qwen-teleporter": {
    kind: "qwen-teleporter",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.bossLaser),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.bossLaserWreck, DEBRIS_ASSETS.bossLaserParts], 0.5),
    },
    label: "QWEN",
    color: 0x55e3cf,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    destroyedVisualOffset: { x: 0, y: -74.375 },
    hitboxOffset: { x: 0, y: -50 },
    hitboxRadii: { x: 70, y: 70 },
    footprintRadii: { x: 90, y: 90 },
    size: 340,
    spriteSize: 340,
    healthBarOffsetY: -294.875,
    baseHp: 70,
    hpPerDifficulty: 9,
    hpVariance: 15,
    speed: 160,
    speedPerDifficulty: 5,
    maxSpeedBonus: 50,
    attackRange: 100,
    attackDamage: 2,
    attackDamageDifficultyDivisor: 3,
    attackCooldownMs: 1_500,
    cooldownReductionPerDifficulty: 30,
    minAttackCooldownMs: 1_000,
    projectileSpeed: 235,
    projectileSpeedPerDifficulty: 15,
    projectileRange: 900,
  },
  "glm-hunter": {
    kind: "glm-hunter",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.bossFortress),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.bossFortressWreck, DEBRIS_ASSETS.bossFortressParts], 0.45),
    },
    label: "GLM",
    color: 0xff8b4d,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    destroyedVisualOffset: { x: 0, y: -78.75 },
    hitboxOffset: { x: 0, y: -50 },
    hitboxRadii: { x: 80, y: 80 },
    footprintRadii: { x: 90, y: 90 },
    size: 400,
    spriteSize: 400,
    healthBarOffsetY: -345.5,
    baseHp: 200,
    hpPerDifficulty: 20,
    hpVariance: 30,
    speed: 320,
    speedPerDifficulty: 5,
    maxSpeedBonus: 50,
    attackRange: 120,
    attackDamage: 3,
    attackDamageDifficultyDivisor: 3,
    attackCooldownMs: 1_200,
    cooldownReductionPerDifficulty: 25,
    minAttackCooldownMs: 1_000,
    projectileSpeed: 210,
    projectileSpeedPerDifficulty: 10,
    projectileRange: 900,
  },
  "kimi-spiral": {
    kind: "kimi-spiral",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.bossMissile),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.bossMissileWreck, DEBRIS_ASSETS.bossMissileParts, DEBRIS_ASSETS.missilePod], 0.5),
    },
    label: "KIMI",
    color: 0x5fe0c0,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    destroyedVisualOffset: { x: 0, y: -70 },
    hitboxOffset: { x: 0, y: -50 },
    hitboxRadii: { x: 66, y: 66 },
    footprintRadii: { x: 90, y: 90 },
    size: 320,
    spriteSize: 320,
    healthBarOffsetY: -278,
    baseHp: 80,
    hpPerDifficulty: 10,
    hpVariance: 14,
    speed: 190,
    speedPerDifficulty: 5,
    maxSpeedBonus: 50,
    attackRange: 80,
    attackDamage: 2,
    attackDamageDifficultyDivisor: 3,
    attackCooldownMs: 1_200,
    cooldownReductionPerDifficulty: 20,
    minAttackCooldownMs: 900,
    projectileSpeed: 220,
    projectileSpeedPerDifficulty: 14,
    projectileRange: 900,
  },
  "hy4-wave": {
    kind: "hy4-wave",
    visual: {
      directions: monsterDirections(MONSTER_FRAMES.bossSiege),
      effects: monsterEffects,
      destroyed: monsterDebris([DEBRIS_ASSETS.bossSiegeWreck, DEBRIS_ASSETS.bossSiegeParts], 0.5),
    },
    label: "Hy4",
    color: 0xffd166,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    destroyedVisualOffset: { x: 0, y: -79.84375 },
    hitboxOffset: { x: 0, y: -50 },
    hitboxRadii: { x: 70, y: 70 },
    footprintRadii: { x: 90, y: 90 },
    size: 365,
    spriteSize: 365,
    healthBarOffsetY: -315.96875,
    baseHp: 80,
    hpPerDifficulty: 16,
    hpVariance: 24,
    speed: 190,
    speedPerDifficulty: 5,
    maxSpeedBonus: 50,
    attackRange: 80,
    attackDamage: 2,
    attackDamageDifficultyDivisor: 3,
    attackCooldownMs: 1_800,
    cooldownReductionPerDifficulty: 25,
    minAttackCooldownMs: 1_400,
    projectileSpeed: 200,
    projectileSpeedPerDifficulty: 20,
    projectileRange: 900,
  },
};

export const MAX_ACTOR_FOOTPRINT = Math.max(
  PLAYER_SPEC.footprintRadii.x, PLAYER_SPEC.footprintRadii.y,
  MAX_REGULAR_MONSTER_FOOTPRINT,
  ...Object.values(BOSS_DEFINITIONS).map(definition => Math.max(definition.footprintRadii.x, definition.footprintRadii.y)),
);

export const GLM_HUNTER_ATTACKS = {
  initialRingDelayMs: 1_800,
  initialChargeDelayMs: 3_500,
  chargeWindupMs: 400,
  chargeRecoveryMs: 400,
} as const;

export const MONSTER_WALK_REFERENCE_SPEED = 120;

export function monsterWalkElapsed(
  walk: SpriteClip,
  now: number,
  seed: number,
  speed: number,
): number {
  const cycle = walk.frames.length * walk.frameDurationMs;
  const phase = ((seed % cycle) + cycle) % cycle;
  const rate = Math.min(2, Math.max(0.5, speed / MONSTER_WALK_REFERENCE_SPEED));
  return phase + now * rate;
}

export interface DecorationDefinition {
  visualOffset: ObjectGeometry["visualOffset"];
  hitboxOffset: ObjectGeometry["hitboxOffset"];
  hitboxRadii: ObjectGeometry["hitboxRadii"];
  footprintRadii: ObjectGeometry["footprintRadii"];
  definitionId: string;
  kind: string;
  visual: ObjectVisualDefinition;
  destructible: boolean;
  obstacle: boolean;
  size: number;
  /** Fraction of the sprite height where opaque content starts; aligns health bars with the visible body. */
  healthBarTop?: number;
}

const plantDebris = [
  DEBRIS_ASSETS.plantGreenPot,
  DEBRIS_ASSETS.plantMagentaPot,
  DEBRIS_ASSETS.plantDryLeaves,
  DEBRIS_ASSETS.plantRoots,
] as const;
const circuitDebris = [DEBRIS_ASSETS.genericCircuit, DEBRIS_ASSETS.genericMetal] as const;
const plantBreak = clip(EFFECT_FRAMES.plantBreak, 1.45, { x: 0.5, y: 0.5 }, 100, {
  light: { color: 0x65e6c4, radiusScale: 0.8, intensity: 0.8 },
});
const barrelExplosion = clip(BARREL_EXPLOSION_FRAMES, 2.8, { x: 0.5, y: 0.84375 }, 1_000 / 12, {
  light: { color: 0xff8b3d, radiusScale: 1.35, intensity: 1.7 },
});
const objectExplosion = explosionEffect(1.5);
const sceneryDamage = damageEffect(0.55);
const plantDebrisClips = plantDebris.map(asset => clip([asset], 1.18));
const circuitDebrisClips = circuitDebris.map(asset => clip([asset], 1.18));

export const DECORATION_DEFINITIONS = {
  plantViolet: {
    definitionId: "plant-violet",
    kind: "plant",
    size: 95,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(30),
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.plantViolet]),
      destroyed: plantDebrisClips,
      animations: { damage: sceneryDamage, destroy: plantBreak },
    },
  },
  plantGreen: {
    definitionId: "plant-green",
    kind: "plant",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(30),
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.plantGreen]),
      destroyed: plantDebrisClips,
      animations: { damage: sceneryDamage, destroy: plantBreak },
    },
  },
  plantMagenta: {
    definitionId: "plant-magenta",
    kind: "plant",
    size: 95,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -15 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(30),
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.plantMagenta]),
      destroyed: plantDebrisClips,
      animations: { damage: sceneryDamage, destroy: plantBreak },
    },
  },
  plantTeal: {
    definitionId: "plant-teal",
    kind: "plant",
    size: 80,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(25),
    footprintRadii: circle(25),
    visual: {
      normal: clip([SCENERY_ASSETS.plantTeal]),
      destroyed: plantDebrisClips,
      animations: { damage: sceneryDamage, destroy: plantBreak },
    },
  },
  plantAmber: {
    definitionId: "plant-amber",
    kind: "plant",
    size: 80,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(25),
    footprintRadii: circle(25),
    visual: {
      normal: clip([SCENERY_ASSETS.plantAmber]),
      destroyed: plantDebrisClips,
      animations: { damage: sceneryDamage, destroy: plantBreak },
    },
  },
  planterDivider: {
    definitionId: "planter-divider",
    kind: "plant",
    size: 200,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 15, y: -60 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 65, y: 25 },
    footprintRadii: { x: 50, y: 20 },
    healthBarTop: 0.0523,
    visual: {
      normal: clip([SCENERY_ASSETS.planterDivider]),
      destroyed: plantDebrisClips,
      animations: { damage: sceneryDamage, destroy: plantBreak },
    },
  },
  barrelRed: {
    definitionId: "barrel-red",
    kind: "barrel",
    size: 82,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -15 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 16, y: 30 },
    footprintRadii: circle(20),
    visual: {
      normal: clip([SCENERY_ASSETS.barrelRed]),
      destroyed: [DEBRIS_ASSETS.barrelRedCrushed, DEBRIS_ASSETS.barrelRedShards, DEBRIS_ASSETS.redBarrelWreck].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: barrelExplosion },
    },
  },
  barrelCoolant: {
    definitionId: "barrel-coolant",
    kind: "barrel",
    size: 82,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -15 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 16, y: 30 },
    footprintRadii: circle(20),
    visual: {
      normal: clip([SCENERY_ASSETS.barrelCoolant]),
      destroyed: [DEBRIS_ASSETS.barrelCoolantRuptured, DEBRIS_ASSETS.blueBarrelWreck, DEBRIS_ASSETS.turquoiseBarrelShards].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: barrelExplosion },
    },
  },
  barrelHazard: {
    definitionId: "barrel-hazard",
    kind: "barrel",
    size: 82,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -15 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 16, y: 30 },
    footprintRadii: circle(20),
    visual: {
      normal: clip([SCENERY_ASSETS.barrelHazard]),
      destroyed: [DEBRIS_ASSETS.barrelHazardBands, DEBRIS_ASSETS.yellowBarrelWreck, DEBRIS_ASSETS.mixedBarrelParts].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: barrelExplosion },
    },
  },
  crateCargo: {
    definitionId: "crate-cargo",
    kind: "crate",
    size: 70,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(30),
    footprintRadii: circle(25),
    visual: {
      normal: clip([SCENERY_ASSETS.crateCargo]),
      destroyed: [clip([DEBRIS_ASSETS.crateCargo], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  crateArmored: {
    definitionId: "crate-armored",
    kind: "crate",
    size: 70,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(30),
    footprintRadii: circle(25),
    visual: {
      normal: clip([SCENERY_ASSETS.crateArmored]),
      destroyed: [clip([DEBRIS_ASSETS.crateArmored], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  crateAmmo: {
    definitionId: "crate-ammo",
    kind: "crate",
    size: 70,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(30),
    footprintRadii: circle(25),
    visual: {
      normal: clip([SCENERY_ASSETS.crateAmmo]),
      destroyed: [clip([DEBRIS_ASSETS.crateAmmo], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  crateMedical: {
    definitionId: "crate-medical",
    kind: "crate",
    size: 70,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: circle(30),
    footprintRadii: circle(25),
    visual: {
      normal: clip([SCENERY_ASSETS.crateMedical]),
      destroyed: [DEBRIS_ASSETS.crateMedical, DEBRIS_ASSETS.whiteMedicalBarrel].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  terminal: {
    definitionId: "terminal",
    kind: "terminal",
    size: 93,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -20  },
    hitboxRadii: { x: 30, y:  40},
    footprintRadii: circle(25),
    visual: {
      normal: clip([SCENERY_ASSETS.terminal]),
      destroyed: [DEBRIS_ASSETS.cyanMonitor, DEBRIS_ASSETS.burntCircuits].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  specimenTank: {
    definitionId: "specimen-tank",
    kind: "machinery",
    size: 155,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -42 },
    hitboxOffset: { x: 0, y: -42 },
    hitboxRadii: { x: 30, y: 60 },
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.specimenTank]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  researchBench: {
    definitionId: "research-bench",
    kind: "machinery",
    size: 135,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 60, y: 30 },
    footprintRadii: { x: 60, y: 25 },
    healthBarTop: 0.2305,
    visual: {
      normal: clip([SCENERY_ASSETS.researchBench]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  reagentRack: {
    definitionId: "reagent-rack",
    kind: "scenery",
    size: 155,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 60, y: 30 },
    footprintRadii: { x: 60, y: 25 },
    healthBarTop: 0.4609,
    visual: {
      normal: clip([SCENERY_ASSETS.reagentRack]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  refrigerator: {
    definitionId: "refrigerator",
    kind: "machinery",
    size: 145,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 35, y: 60 },
    footprintRadii: circle(35),
    visual: {
      normal: clip([SCENERY_ASSETS.refrigerator]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  roboticManipulator: {
    definitionId: "robotic-manipulator",
    kind: "machinery",
    size: 145,
    destructible: true,
    obstacle: true,
    visualOffset: { x: -15, y: -40 },
    hitboxOffset: { x: -5, y: -50 },
    hitboxRadii: {x: 35, y: 50 },
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.roboticManipulator]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  medicalCabinet: {
    definitionId: "medical-cabinet",
    kind: "machinery",
    size: 145,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 35, y: 60 },
    footprintRadii: { x: 35, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.medicalCabinet]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  diagnosticScanner: {
    definitionId: "diagnostic-scanner",
    kind: "machinery",
    size: 190,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -40 },
    hitboxRadii: { x: 60, y: 70 },
    footprintRadii: { x: 35, y: 45 },
    visual: {
      normal: clip([SCENERY_ASSETS.diagnosticScanner]),
      destroyed: [clip([DEBRIS_ASSETS.medicalMonitor], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  medicalBed: {
    definitionId: "medical-bed",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 30, y: 45 },
    footprintRadii: { x: 30, y: 40 },
    visual: {
      normal: clip([SCENERY_ASSETS.medicalBed]),
      destroyed: [clip([DEBRIS_ASSETS.medicalBed], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  vitalsMonitor: {
    definitionId: "vitals-monitor",
    kind: "machinery",
    size: 70,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -15 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 30, y: 25 },
    footprintRadii: { x: 30, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.vitalsMonitor]),
      destroyed: [clip([DEBRIS_ASSETS.medicalMonitor], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  ivStand: {
    definitionId: "iv-stand",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 15, y: 60 },
    footprintRadii: circle(20),
    visual: {
      normal: clip([SCENERY_ASSETS.ivStand]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  surgicalCart: {
    definitionId: "surgical-cart",
    kind: "machinery",
    size: 110,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 40, y: 35 },
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.surgicalCart]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  resuscitationUnit: {
    definitionId: "resuscitation-unit",
    kind: "machinery",
    size: 110,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: circle(40),
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.resuscitationUnit]),
      destroyed: [clip([DEBRIS_ASSETS.medicalMonitor], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  decontaminationShower: {
    definitionId: "decontamination-shower",
    kind: "machinery",
    size: 145,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 40, y: 60 },
    footprintRadii: circle(35),
    visual: {
      normal: clip([SCENERY_ASSETS.decontaminationShower]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  supplyTrolley: {
    definitionId: "supply-trolley",
    kind: "machinery",
    size: 110,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 40, y: 35 },
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.supplyTrolley]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  pipeValve: {
    definitionId: "pipe-valve",
    kind: "scenery",
    size: 95,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 30, y: 15 },
    footprintRadii: { x: 30, y: 15 },
    healthBarTop: 0.5742,
    visual: {
      normal: clip([SCENERY_ASSETS.pipeValve]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  pipeElbow: {
    definitionId: "pipe-elbow",
    kind: "scenery",
    size: 70,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: 0 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: circle(30),
    footprintRadii: circle(30),
    healthBarTop: 0.1367,
    visual: {
      normal: clip([SCENERY_ASSETS.pipeElbow]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  coiledCables: {
    definitionId: "coiled-cables",
    kind: "scenery",
    size: 70,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 30, y: 25 },
    footprintRadii: { x: 30, y: 25 },
    healthBarTop: 0.3867,
    visual: {
      normal: clip([SCENERY_ASSETS.coiledCables]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  monitorBank: {
    definitionId: "monitor-bank",
    kind: "machinery",
    size: 155,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 70, y: 35 },
    footprintRadii: { x: 60, y: 30 },
    healthBarTop: 0.3945,
    visual: {
      normal: clip([SCENERY_ASSETS.monitorBank]),
      destroyed: [clip([DEBRIS_ASSETS.cyanMonitor], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  serverRack: {
    definitionId: "server-rack",
    kind: "machinery",
    size: 155,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -35 },
    hitboxRadii: { x: 35, y: 60 },
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.serverRack]),
      destroyed: [DEBRIS_ASSETS.electronicsCabinet, DEBRIS_ASSETS.burntCircuits].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  radarDisplay: {
    definitionId: "radar-display",
    kind: "machinery",
    size: 80,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -15 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: circle(30),
    footprintRadii: circle(30),
    healthBarTop: 0.3125,
    visual: {
      normal: clip([SCENERY_ASSETS.radarDisplay]),
      destroyed: [clip([DEBRIS_ASSETS.cyanMonitor], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  operatorTerminal: {
    definitionId: "operator-terminal",
    kind: "machinery",
    size: 100,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 40, y: 35 },
    footprintRadii: { x: 35, y: 25 },
    healthBarTop: 0.1367,
    visual: {
      normal: clip([SCENERY_ASSETS.operatorTerminal]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  communicationsCabinet: {
    definitionId: "communications-cabinet",
    kind: "machinery",
    size: 155,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -25 },
    hitboxRadii: { x: 30, y: 50 },
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.communicationsCabinet]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  hologramTable: {
    definitionId: "hologram-table",
    kind: "machinery",
    size: 125,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 40, y: 35 },
    footprintRadii: { x: 40, y: 30 },
    healthBarTop: 0.4102,
    visual: {
      normal: clip([SCENERY_ASSETS.hologramTable]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  conduitJunction: {
    definitionId: "conduit-junction",
    kind: "scenery",
    size: 120,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 35, y: 15 },
    footprintRadii: { x: 35, y: 15 },
    healthBarTop: 0.6602,
    visual: {
      normal: clip([SCENERY_ASSETS.conduitJunction]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  powerCabinet: {
    definitionId: "power-cabinet",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 40, y: 50 },
    footprintRadii: { x: 40, y: 30 },
    visual: {
      normal: clip([SCENERY_ASSETS.powerCabinet]),
      destroyed: [clip([DEBRIS_ASSETS.electronicsCabinet], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  floorCables: {
    definitionId: "floor-cables",
    kind: "scenery",
    size: 120,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 35, y: 15 },
    footprintRadii: { x: 35, y: 15 },
    healthBarTop: 0.6992,
    visual: {
      normal: clip([SCENERY_ASSETS.floorCables]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  reactorPylon: {
    definitionId: "reactor-pylon",
    kind: "machinery",
    size: 180,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 45, y: 60 },
    footprintRadii: { x: 40, y: 30 },
    visual: {
      normal: clip([SCENERY_ASSETS.reactorPylon]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  coolantPump: {
    definitionId: "coolant-pump",
    kind: "machinery",
    size: 156,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 50, y: 40 },
    footprintRadii: { x: 45, y: 25 },
    healthBarTop: 0.3242,
    visual: {
      normal: clip([SCENERY_ASSETS.coolantPump]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  energyCapacitor: {
    definitionId: "energy-capacitor",
    kind: "machinery",
    size: 180,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -45 },
    hitboxOffset: { x: 0, y: -35 },
    hitboxRadii: { x: 50, y: 70 },
    footprintRadii: { x: 45, y: 30 },
    visual: {
      normal: clip([SCENERY_ASSETS.energyCapacitor]),
      destroyed: [clip([DEBRIS_ASSETS.purpleEnergyCoil], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  barricade: {
    definitionId: "barricade",
    kind: "machinery",
    size: 155,
    destructible: false,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 50, y: 25 },
    footprintRadii: { x: 50, y: 15 },
    healthBarTop: 0.5508,
    visual: {
      normal: clip([SCENERY_ASSETS.barricade]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  maintenanceRack: {
    definitionId: "maintenance-rack",
    kind: "machinery",
    size: 155,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 50, y: 35 },
    footprintRadii: { x: 50, y: 15 },
    healthBarTop: 0.3359,
    visual: {
      normal: clip([SCENERY_ASSETS.maintenanceRack]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  hydraulicSupport: {
    definitionId: "hydraulic-support",
    kind: "machinery",
    size: 150,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -45 },
    hitboxOffset: { x: 0, y: -40 },
    hitboxRadii: { x: 30, y: 70 },
    footprintRadii: { x: 40, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.hydraulicSupport]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  pipeManifold: {
    definitionId: "pipe-manifold",
    kind: "scenery",
    size: 120,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 40, y: 20 },
    footprintRadii: { x: 40, y: 20 },
    healthBarTop: 0.5781,
    visual: {
      normal: clip([SCENERY_ASSETS.pipeManifold]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  damagedFuseCabinet: {
    definitionId: "damaged-fuse-cabinet",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 40, y: 30 },
    footprintRadii: { x: 40, y: 15 },
    healthBarTop: 0.3711,
    visual: {
      normal: clip([SCENERY_ASSETS.damagedFuseCabinet]),
      destroyed: [DEBRIS_ASSETS.electronicsCabinet, DEBRIS_ASSETS.burntCircuits].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  batteryBank: {
    definitionId: "battery-bank",
    kind: "machinery",
    size: 180,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -45 },
    hitboxOffset: { x: 0, y: -18 },
    hitboxRadii: { x: 65, y: 35 },
    footprintRadii: { x: 65, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.batteryBank]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  coolantReservoir: {
    definitionId: "coolant-reservoir",
    kind: "machinery",
    size: 145,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 45, y: 60 },
    footprintRadii: { x: 45, y: 30 },
    visual: {
      normal: clip([SCENERY_ASSETS.coolantReservoir]),
      destroyed: [clip([DEBRIS_ASSETS.motor], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  fuelPumpSkid: {
    definitionId: "fuel-pump-skid",
    kind: "machinery",
    size: 250,
    destructible: true,
    obstacle: true,
    visualOffset: { x: -20, y: -80 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 75, y: 60 },
    footprintRadii: { x: 70, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.fuelPumpSkid]),
      destroyed: [DEBRIS_ASSETS.turbine, DEBRIS_ASSETS.greenChemicalBarrel, DEBRIS_ASSETS.orangeFuelBarrel].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  heavyMotor: {
    definitionId: "heavy-motor",
    kind: "machinery",
    size: 160,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -45 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 65, y: 30 },
    footprintRadii: { x: 60, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.heavyMotor]),
      destroyed: [clip([DEBRIS_ASSETS.motor], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  engineToolCart: {
    definitionId: "engine-tool-cart",
    kind: "machinery",
    size: 110,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 40, y: 35 },
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.engineToolCart]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  pressureGauge: {
    definitionId: "pressure-gauge",
    kind: "machinery",
    size: 200,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -55 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 75, y: 50 },
    footprintRadii: { x: 70, y: 35 },
    visual: {
      normal: clip([SCENERY_ASSETS.pressureGauge]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  turbineGenerator: {
    definitionId: "turbine-generator",
    kind: "machinery",
    size: 160,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 65, y: 35 },
    footprintRadii: { x: 60, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.turbineGenerator]),
      destroyed: [clip([DEBRIS_ASSETS.turbine], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  ventilationBlower: {
    definitionId: "ventilation-blower",
    kind: "machinery",
    size: 160,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 65, y: 60 },
    footprintRadii: { x: 60, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.ventilationBlower]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  heatExchanger: {
    definitionId: "heat-exchanger",
    kind: "machinery",
    size: 160,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 5, y: -40 },
    hitboxOffset: { x: 5, y: -30 },
    hitboxRadii: { x: 50, y: 60 },
    footprintRadii: { x: 35, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.heatExchanger]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  evacuationKiosk: {
    definitionId: "evacuation-kiosk",
    kind: "machinery",
    size: 100,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -15 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 30, y: 40 },
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.evacuationKiosk]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  dockingClamp: {
    definitionId: "docking-clamp",
    kind: "machinery",
    size: 150,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 60, y: 25 },
    footprintRadii: { x: 60, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.dockingClamp]),
      destroyed: [clip([DEBRIS_ASSETS.dockingClamp], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  oxygenTankRack: {
    definitionId: "oxygen-tank-rack",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -35 },
    hitboxRadii: { x: 50, y: 55 },
    footprintRadii: { x: 50, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.oxygenTankRack]),
      destroyed: [clip([DEBRIS_ASSETS.dockingClamp], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  openEscapeCapsule: {
    definitionId: "open-escape-capsule",
    kind: "machinery",
    size: 220,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -70 },
    hitboxOffset: { x: 0, y: -55 },
    hitboxRadii: { x: 45, y: 90 },
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.openEscapeCapsule]),
      destroyed: [clip([DEBRIS_ASSETS.escapePod], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  sealedEscapeCapsule: {
    definitionId: "sealed-escape-capsule",
    kind: "machinery",
    size: 200,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -65 },
    hitboxOffset: { x: 0, y: -55 },
    hitboxRadii: { x: 45, y: 80 },
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.sealedEscapeCapsule]),
      destroyed: [clip([DEBRIS_ASSETS.escapePod], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  emergencyBeacon: {
    definitionId: "emergency-beacon",
    kind: "machinery",
    size: 130,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -35 },
    hitboxRadii: { x: 20, y: 50 },
    footprintRadii: { x: 20, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.emergencyBeacon]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  lifeboatPod: {
    definitionId: "lifeboat-pod",
    kind: "machinery",
    size: 200,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -50 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 80, y: 40 },
    footprintRadii: { x: 80, y: 30 },
    visual: {
      normal: clip([SCENERY_ASSETS.lifeboatPod]),
      destroyed: [clip([DEBRIS_ASSETS.escapePod], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  survivalCase: {
    definitionId: "survival-case",
    kind: "machinery",
    size: 85,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -10 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 35, y: 25 },
    footprintRadii: circle(30),
    visual: {
      normal: clip([SCENERY_ASSETS.survivalCase]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  boardingSteps: {
    definitionId: "boarding-steps",
    kind: "scenery",
    size: 155,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 50, y: 50 },
    footprintRadii: { x: 50, y: 35 },
    visual: {
      normal: clip([SCENERY_ASSETS.boardingSteps]),
      destroyed: [clip([DEBRIS_ASSETS.pallet], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  cargoPallet: {
    definitionId: "cargo-pallet",
    kind: "scenery",
    size: 155,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 50, y: 25 },
    footprintRadii: { x: 50, y: 15 },
    visual: {
      normal: clip([SCENERY_ASSETS.cargoPallet]),
      destroyed: [clip([DEBRIS_ASSETS.pallet], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  cargoShelf: {
    definitionId: "cargo-shelf",
    kind: "machinery",
    size: 165,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -50 },
    hitboxOffset: { x: 0, y: -25 },
    hitboxRadii: { x: 60, y: 45 },
    footprintRadii: { x: 60, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.cargoShelf]),
      destroyed: [clip([DEBRIS_ASSETS.storageShelf], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  loadingGantry: {
    definitionId: "loading-gantry",
    kind: "machinery",
    size: 170,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -45 },
    hitboxOffset: { x: 0, y: -25 },
    hitboxRadii: { x: 70, y: 45 },
    footprintRadii: { x: 70, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.loadingGantry]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  steelCrateStack: {
    definitionId: "steel-crate-stack",
    kind: "machinery",
    size: 135,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 60, y: 50 },
    footprintRadii: { x: 60, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.steelCrateStack]),
      destroyed: [clip([DEBRIS_ASSETS.storageShelf], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  toolLocker: {
    definitionId: "tool-locker",
    kind: "machinery",
    size: 135,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 45, y: 55 },
    footprintRadii: { x: 40, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.toolLocker]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  weighingPlatform: {
    definitionId: "weighing-platform",
    kind: "machinery",
    size: 105,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -25 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 35, y: 35 },
    footprintRadii: { x: 35, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.weighingPlatform]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  canisterRack: {
    definitionId: "canister-rack",
    kind: "machinery",
    size: 160,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -45 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 65, y: 45 },
    footprintRadii: { x: 65, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.canisterRack]),
      destroyed: [DEBRIS_ASSETS.mixedBarrelParts].map(asset => clip([asset], 1.18)),
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  palletJack: {
    definitionId: "pallet-jack",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 50, y: 20 },
    footprintRadii: { x: 50, y: 15 },
    visual: {
      normal: clip([SCENERY_ASSETS.palletJack]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  luggageStack: {
    definitionId: "luggage-stack",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 50, y: 35 },
    footprintRadii: { x: 50, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.luggageStack]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  entertainmentScreen: {
    definitionId: "entertainment-screen",
    kind: "machinery",
    size: 150,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 60, y: 40 },
    footprintRadii: { x: 60, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.entertainmentScreen]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  bunkBed: {
    definitionId: "bunk-bed",
    kind: "machinery",
    size: 150,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: { x: 60, y: 50 },
    footprintRadii: { x: 60, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.bunkBed]),
      destroyed: [clip([DEBRIS_ASSETS.bunk], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  metalChair: {
    definitionId: "metal-chair",
    kind: "machinery",
    size: 95,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 20, y: 30 },
    footprintRadii: circle(20),
    visual: {
      normal: clip([SCENERY_ASSETS.metalChair]),
      destroyed: [clip([DEBRIS_ASSETS.kitchenette], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  showerSink: {
    definitionId: "shower-sink",
    kind: "machinery",
    size: 160,
    destructible: true,
    obstacle: true,
    visualOffset: { x: -5, y: -45 },
    hitboxOffset: { x: 0, y: -25 },
    hitboxRadii: { x: 60, y: 50 },
    footprintRadii: { x: 60, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.showerSink]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  personalLocker: {
    definitionId: "personal-locker",
    kind: "machinery",
    size: 120,
    destructible: true,
    obstacle: true,
    visualOffset: { x: -15, y: -30 },
    hitboxOffset: { x: 0, y: -30 },
    hitboxRadii: { x: 25, y: 50 },
    footprintRadii: { x: 25, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.personalLocker]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  sofa: {
    definitionId: "sofa",
    kind: "machinery",
    size: 140,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: -5 },
    hitboxRadii: { x: 60, y: 30 },
    footprintRadii: { x: 60, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.sofa]),
      destroyed: [clip([DEBRIS_ASSETS.bunk], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  kitchenette: {
    definitionId: "kitchenette",
    kind: "machinery",
    size: 160,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 0, y: -40 },
    hitboxOffset: { x: 0, y: -25 },
    hitboxRadii: { x: 60, y: 50 },
    footprintRadii: { x: 60, y: 25 },
    visual: {
      normal: clip([SCENERY_ASSETS.kitchenette]),
      destroyed: [clip([DEBRIS_ASSETS.kitchenette], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  messTable: {
    definitionId: "mess-table",
    kind: "machinery",
    size: 130,
    destructible: true,
    obstacle: true,
    visualOffset: { x: 5, y: -35 },
    hitboxOffset: { x: 0, y: -15 },
    hitboxRadii: { x: 45, y: 30 },
    footprintRadii: { x: 45, y: 15 },
    visual: {
      normal: clip([SCENERY_ASSETS.messTable]),
      destroyed: [clip([DEBRIS_ASSETS.kitchenette], 1.18)],
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  cableTrunk: {
    definitionId: "cable-trunk",
    kind: "scenery",
    size: 120,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -30 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 50, y: 20 },
    footprintRadii: { x: 50, y: 15 },
    healthBarTop: 0.6445,
    visual: {
      normal: clip([SCENERY_ASSETS.cableTrunk]),
      destroyed: circuitDebrisClips,
      animations: { damage: sceneryDamage, destroy: objectExplosion },
    },
  },
  spawner: {
    definitionId: "monster-spawner",
    kind: "monster-spawner",
    size: 205,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -55 },
    hitboxOffset: { x: 0, y: -10 },
    hitboxRadii: { x: 45, y: 35 },
    footprintRadii: { x: 40, y: 30 },
    healthBarTop: 0.5273,
    visual: {
      normal: clip([SCENERY_ASSETS.spawnerDormant]),
      destroyed: circuitDebris.map(asset => clip([asset], 0.68)),
      animations: {
        damage: damageEffect(0.4),
        destroy: explosionEffect(0.72),
        spawn: clip([
          SCENERY_ASSETS.spawnerDormant,
          SCENERY_ASSETS.spawnerCharging,
          SCENERY_ASSETS.spawnerDischarge,
          SCENERY_ASSETS.spawnerReady,
        ], 1, undefined, 125, {
          holdLast: true,
          eventFrame: 2,
          light: { color: 0xc07cff, radiusScale: 0.75, intensity: 0.85 },
        }),
      },
    },
  },
  contentBrowser: {
    definitionId: "content-browser",
    kind: "content-browser",
    size: 135,
    destructible: true,
    obstacle: false,
    visualOffset: { x: 0, y: -35 },
    hitboxOffset: { x: 0, y: 0 },
    hitboxRadii: { x: 25, y: 20 },
    footprintRadii: { x: 25, y: 20 },
    visual: {
      normal: clip([SCENERY_ASSETS.contentBrowserOff]),
      destroyed: circuitDebris.map(asset => clip([asset], 0.8)),
      animations: {
        damage: damageEffect(0.4),
        destroy: explosionEffect(0.72),
        spawn: clip([
          SCENERY_ASSETS.contentBrowserTurning,
          SCENERY_ASSETS.contentBrowserOn,
        ], 1, undefined, 180, { holdLast: true }),
      },
    },
  },
  debrisCircuit: {
    definitionId: "debris-circuit",
    kind: "debris",
    size: 90,
    destructible: false,
    obstacle: false,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: circle(20),
    footprintRadii: circle(20),
    visual: {
      normal: clip([DEBRIS_ASSETS.genericCircuit]),
      destroyed: [],
    },
  },
  debrisMetal: {
    definitionId: "debris-metal",
    kind: "debris",
    size: 90,
    destructible: false,
    obstacle: false,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: -20 },
    hitboxRadii: circle(20),
    footprintRadii: circle(20),
    visual: {
      normal: clip([DEBRIS_ASSETS.genericMetal]),
      destroyed: [],
    },
  },
  pedestal: {
    definitionId: "weapon-pedestal",
    kind: "weapon-pedestal",
    size: 108,
    destructible: false,
    obstacle: false,
    visualOffset: { x: 0, y: -20 },
    hitboxOffset: { x: 0, y: 10 },
    hitboxRadii: { x: 30, y: 20 },
    footprintRadii: { x: 30, y: 20 },
    visual: {
      normal: clip([ASSETS.pedestal]),
      destroyed: [],
    },
  },
} as const satisfies Record<string, DecorationDefinition>;

export const OBSTACLE_DEFINITIONS: readonly DecorationDefinition[] = Object.values(DECORATION_DEFINITIONS)
  .filter(definition => definition.obstacle);

export const SCENERY_DEFINITIONS: readonly DecorationDefinition[] = [
  DECORATION_DEFINITIONS.debrisCircuit,
  DECORATION_DEFINITIONS.debrisMetal,
  DECORATION_DEFINITIONS.reagentRack,
  DECORATION_DEFINITIONS.pipeValve,
  DECORATION_DEFINITIONS.pipeElbow,
  DECORATION_DEFINITIONS.coiledCables,
  DECORATION_DEFINITIONS.conduitJunction,
  DECORATION_DEFINITIONS.floorCables,
  DECORATION_DEFINITIONS.pipeManifold,
  DECORATION_DEFINITIONS.cableTrunk,
  DECORATION_DEFINITIONS.cargoPallet,
  DECORATION_DEFINITIONS.boardingSteps,
];

export type RoomSceneryTheme = "lab" | "control" | "arena" | "medical" | "engine" | "escape" | "storage" | "living";

export interface WeightedDecorationDefinition {
  definition: DecorationDefinition;
  weight: number;
}

export interface RoomSceneryThemeDefinition {
  primary: readonly WeightedDecorationDefinition[];
  accents: readonly WeightedDecorationDefinition[];
  primaryPercent: number;
}

const weighted = (
  definition: DecorationDefinition,
  weight = 1,
): WeightedDecorationDefinition => ({ definition, weight });

export const ROOM_SCENERY_THEMES: Readonly<Record<RoomSceneryTheme, RoomSceneryThemeDefinition>> = {
  lab: {
    primaryPercent: 78,
    primary: [
      weighted(DECORATION_DEFINITIONS.crateMedical, 6),
      weighted(DECORATION_DEFINITIONS.specimenTank, 2),
      weighted(DECORATION_DEFINITIONS.researchBench, 2),
      weighted(DECORATION_DEFINITIONS.refrigerator, 2),
      weighted(DECORATION_DEFINITIONS.roboticManipulator),
      weighted(DECORATION_DEFINITIONS.reagentRack),
      weighted(DECORATION_DEFINITIONS.pipeValve),
      weighted(DECORATION_DEFINITIONS.coiledCables),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.barrelCoolant, 2),
      weighted(DECORATION_DEFINITIONS.plantGreen),
      weighted(DECORATION_DEFINITIONS.crateCargo),
      weighted(DECORATION_DEFINITIONS.debrisCircuit),
    ],
  },
  control: {
    primaryPercent: 78,
    primary: [
      weighted(DECORATION_DEFINITIONS.terminal, 3),
      weighted(DECORATION_DEFINITIONS.monitorBank, 2),
      weighted(DECORATION_DEFINITIONS.serverRack, 2),
      weighted(DECORATION_DEFINITIONS.radarDisplay),
      weighted(DECORATION_DEFINITIONS.operatorTerminal, 2),
      weighted(DECORATION_DEFINITIONS.communicationsCabinet),
      weighted(DECORATION_DEFINITIONS.hologramTable),
      weighted(DECORATION_DEFINITIONS.conduitJunction),
      weighted(DECORATION_DEFINITIONS.powerCabinet),
      weighted(DECORATION_DEFINITIONS.floorCables),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.crateArmored, 2),
      weighted(DECORATION_DEFINITIONS.crateAmmo, 2),
      weighted(DECORATION_DEFINITIONS.plantViolet),
      weighted(DECORATION_DEFINITIONS.debrisCircuit),
    ],
  },
  arena: {
    primaryPercent: 78,
    primary: [
      weighted(DECORATION_DEFINITIONS.reactorPylon, 2),
      weighted(DECORATION_DEFINITIONS.coolantPump, 2),
      weighted(DECORATION_DEFINITIONS.energyCapacitor, 2),
      weighted(DECORATION_DEFINITIONS.barricade, 3),
      weighted(DECORATION_DEFINITIONS.maintenanceRack),
      weighted(DECORATION_DEFINITIONS.hydraulicSupport),
      weighted(DECORATION_DEFINITIONS.pipeManifold),
      weighted(DECORATION_DEFINITIONS.damagedFuseCabinet),
      weighted(DECORATION_DEFINITIONS.cableTrunk),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.barrelHazard, 3),
      weighted(DECORATION_DEFINITIONS.crateAmmo, 2),
      weighted(DECORATION_DEFINITIONS.crateArmored),
      weighted(DECORATION_DEFINITIONS.debrisMetal),
    ],
  },
  medical: {
    primaryPercent: 82,
    primary: [
      weighted(DECORATION_DEFINITIONS.medicalBed, 3),
      weighted(DECORATION_DEFINITIONS.medicalCabinet, 2),
      weighted(DECORATION_DEFINITIONS.diagnosticScanner, 2),
      weighted(DECORATION_DEFINITIONS.vitalsMonitor, 2),
      weighted(DECORATION_DEFINITIONS.ivStand),
      weighted(DECORATION_DEFINITIONS.surgicalCart),
      weighted(DECORATION_DEFINITIONS.resuscitationUnit),
      weighted(DECORATION_DEFINITIONS.decontaminationShower),
      weighted(DECORATION_DEFINITIONS.supplyTrolley),
      weighted(DECORATION_DEFINITIONS.crateMedical, 2),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.crateCargo),
      weighted(DECORATION_DEFINITIONS.plantTeal),
      weighted(DECORATION_DEFINITIONS.debrisCircuit),
    ],
  },
  engine: {
    primaryPercent: 82,
    primary: [
      weighted(DECORATION_DEFINITIONS.turbineGenerator, 2),
      weighted(DECORATION_DEFINITIONS.batteryBank, 2),
      weighted(DECORATION_DEFINITIONS.coolantReservoir, 2),
      weighted(DECORATION_DEFINITIONS.fuelPumpSkid),
      weighted(DECORATION_DEFINITIONS.heavyMotor, 2),
      weighted(DECORATION_DEFINITIONS.engineToolCart),
      weighted(DECORATION_DEFINITIONS.pressureGauge),
      weighted(DECORATION_DEFINITIONS.ventilationBlower),
      weighted(DECORATION_DEFINITIONS.heatExchanger),
      weighted(DECORATION_DEFINITIONS.coolantPump),
      weighted(DECORATION_DEFINITIONS.powerCabinet),
      weighted(DECORATION_DEFINITIONS.damagedFuseCabinet),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.barrelCoolant, 2),
      weighted(DECORATION_DEFINITIONS.pipeValve),
      weighted(DECORATION_DEFINITIONS.cableTrunk),
      weighted(DECORATION_DEFINITIONS.debrisMetal),
    ],
  },
  escape: {
    primaryPercent: 82,
    primary: [
      weighted(DECORATION_DEFINITIONS.evacuationKiosk, 2),
      weighted(DECORATION_DEFINITIONS.dockingClamp),
      weighted(DECORATION_DEFINITIONS.oxygenTankRack),
      weighted(DECORATION_DEFINITIONS.openEscapeCapsule, 2),
      weighted(DECORATION_DEFINITIONS.sealedEscapeCapsule, 2),
      weighted(DECORATION_DEFINITIONS.emergencyBeacon),
      weighted(DECORATION_DEFINITIONS.lifeboatPod),
      weighted(DECORATION_DEFINITIONS.survivalCase),
      weighted(DECORATION_DEFINITIONS.boardingSteps),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.crateCargo, 2),
      weighted(DECORATION_DEFINITIONS.barrelHazard),
      weighted(DECORATION_DEFINITIONS.floorCables),
      weighted(DECORATION_DEFINITIONS.debrisMetal),
    ],
  },
  storage: {
    primaryPercent: 82,
    primary: [
      weighted(DECORATION_DEFINITIONS.cargoShelf, 2),
      weighted(DECORATION_DEFINITIONS.loadingGantry),
      weighted(DECORATION_DEFINITIONS.steelCrateStack, 2),
      weighted(DECORATION_DEFINITIONS.toolLocker),
      weighted(DECORATION_DEFINITIONS.weighingPlatform),
      weighted(DECORATION_DEFINITIONS.canisterRack),
      weighted(DECORATION_DEFINITIONS.palletJack),
      weighted(DECORATION_DEFINITIONS.luggageStack),
      weighted(DECORATION_DEFINITIONS.cargoPallet),
      weighted(DECORATION_DEFINITIONS.crateCargo, 3),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.crateArmored),
      weighted(DECORATION_DEFINITIONS.crateAmmo),
      weighted(DECORATION_DEFINITIONS.barrelRed),
      weighted(DECORATION_DEFINITIONS.debrisMetal),
    ],
  },
  living: {
    primaryPercent: 82,
    primary: [
      weighted(DECORATION_DEFINITIONS.bunkBed, 2),
      weighted(DECORATION_DEFINITIONS.entertainmentScreen),
      weighted(DECORATION_DEFINITIONS.metalChair, 2),
      weighted(DECORATION_DEFINITIONS.showerSink),
      weighted(DECORATION_DEFINITIONS.personalLocker),
      weighted(DECORATION_DEFINITIONS.sofa, 2),
      weighted(DECORATION_DEFINITIONS.kitchenette),
      weighted(DECORATION_DEFINITIONS.messTable, 2),
      weighted(DECORATION_DEFINITIONS.planterDivider),
    ],
    accents: [
      weighted(DECORATION_DEFINITIONS.plantGreen, 2),
      weighted(DECORATION_DEFINITIONS.plantAmber),
      weighted(DECORATION_DEFINITIONS.crateCargo),
      weighted(DECORATION_DEFINITIONS.debrisCircuit),
    ],
  },
};

export const MAX_REGULAR_MONSTER_RADIUS = Math.max(
  ...Object.values(REGULAR_MONSTER_DEFINITIONS).flatMap(definition => [definition.hitboxRadii.x, definition.hitboxRadii.y]),
);

export interface LootDefinition {
  asset: string;
  size: number;
  footprintRadii: ObjectGeometry["footprintRadii"];
  frames?: readonly string[];
  frameDurationMs?: number;
}

export const LOOT_DEFINITIONS: Record<Exclude<LootKind, "weapon">, LootDefinition> = {
  credit: {
    asset: ASSETS.lootCredit,
    frames: LOOT_RAM_FRAMES,
    frameDurationMs: 200,
    size: 50,
    footprintRadii: circle(20),
  },
  crystal: { asset: ASSETS.lootCrystal, size: 63, footprintRadii: circle(20) },
  core: { asset: ASSETS.lootCore, size: 63, footprintRadii: circle(20) },
  energy: { asset: ASSETS.lootEnergy, size: 63, footprintRadii: circle(20) },
  medkit: { asset: ASSETS.lootMedkit, size: 63, footprintRadii: circle(20) },
};

export const WEAPON_PICKUP_DEFINITIONS: Record<WeaponPlacement, { size: number; yOffset: number; footprintRadii: ObjectGeometry["footprintRadii"] }> = {
  pedestal: { size: 92, yOffset: 0, footprintRadii: circle(20) },
  floor: { size: 74, yOffset: 0, footprintRadii: circle(20) },
};

export const WEAPON_VISUAL_DEFINITIONS: Record<WeaponKind, { asset: string; origin: { x: number; y: number }; pedestalYOffset: number }> = {
  "pulse-rifle": { asset: WEAPON_ASSETS["pulse-rifle"], origin: { x: 0.5, y: 0.656 }, pedestalYOffset: -49 },
  "byte-repeater": { asset: WEAPON_ASSETS["byte-repeater"], origin: { x: 0.5, y: 0.744 }, pedestalYOffset: -41 },
  "scatter-array": { asset: WEAPON_ASSETS["scatter-array"], origin: { x: 0.5, y: 0.801 }, pedestalYOffset: -36 },
  "fork-driver": { asset: WEAPON_ASSETS["fork-driver"], origin: { x: 0.5, y: 0.77 }, pedestalYOffset: -39 },
  trident: { asset: WEAPON_ASSETS.trident, origin: { x: 0.5, y: 0.768 }, pedestalYOffset: -39 },
  "needle-rail": { asset: WEAPON_ASSETS["needle-rail"], origin: { x: 0.5, y: 0.836 }, pedestalYOffset: -32 },
  "packet-lobber": { asset: WEAPON_ASSETS["packet-lobber"], origin: { x: 0.5, y: 0.777 }, pedestalYOffset: -38 },
  "cross-compiler": { asset: WEAPON_ASSETS["cross-compiler"], origin: { x: 0.5, y: 0.771 }, pedestalYOffset: -38 },
  "nova-cache": { asset: WEAPON_ASSETS["nova-cache"], origin: { x: 0.5, y: 0.762 }, pedestalYOffset: -39 },
  "helix-emitter": { asset: WEAPON_ASSETS["helix-emitter"], origin: { x: 0.5, y: 0.744 }, pedestalYOffset: -41 },
  "sideband-projector": { asset: WEAPON_ASSETS["sideband-projector"], origin: { x: 0.5, y: 0.77 }, pedestalYOffset: -39 },
};

export const PORTAL_DEFINITION = {
  obstacle: false,
  frames: PORTAL_FRAMES,
  size: 150,
  visualOffset: { x: 0, y: -30 },
  hitboxOffset: { x: 0, y: 0 },
  hitboxRadii: circle(0),
  footprintRadii: { x: 40, y: 25 },
  origin: { x: 0.5, y: 0.875 },
  // Depth-ordering anchor sits slightly above the sprite anchor so actors
  // near the pedestal base render in front of the portal.
  orderingOffsetY: -30,
  // Spawn outside the activation footprint to avoid re-entering immediately.
  spawnOffset: { x: 0, y: 40 },
} as const;

export function weaponAsset(kind: WeaponKind): string {
  return WEAPON_VISUAL_DEFINITIONS[kind].asset;
}
